name: Build Docker Image (Release)

on:
  push:
    # trigger on version tag push
    tags:
      - "v*"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Metadata: Git"
        id: git-meta
        uses: 'penguin-statistics/actions/git-meta@main'
      
      - name: "Docker: Build and Push Image"
        id: ghcr-docker
        uses: 'penguin-statistics/actions/ghcr-docker@main'
        with:
          version: ${{ steps.git-meta.outputs.version }}
          repository: 'penguin-statistics/livehouse'
          build-args: |
            BUILD_DOCS_COMMIT=fb08b08f5f97e89b2407e56c20b0707f19dc8f32
            BUILD_WEB_COMMIT=451e3aef9973f6cd0d58cd60aa75961acf460b51

      - name: "Release: Call Dispatcher"
        id: release-dispatcher
        uses: 'penguin-statistics/actions/release-dispatcher@main'
        with:
          version: ${{ steps.git-meta.outputs.version }}
          use-ghrelease: true
          # use-manifestbot: true
          # manifestbot-file-path: 'applications/livehouse/values-prod.yaml'
          # manifestbot-token: ${{ secrets.PAT_FOR_MANIFESTBOT }}
